name: Echo issues and context
on: [push, workflow_dispatch]

jobs:
  issues:
    runs-on: ubuntu-latest
    steps:
      - name: Echo repo issue
        run: echo "${{ toJSON(issues) }}"
      - name: Echo Github context
        run: echo "${{ toJSON(github) }}"